---
version: "3"
services:
  frontend:
    build: ./type_ahead/frontend
    image: frontend:latest
    expose:
      - "3000"
    # {HOST PORT}: {CONTAINER PORT}
    ports:
      - "3000:3000"

  backend:
    build: ./type_ahead/backend
    image: backend:latest
    expose:
      - "5000"
    ports:
      - "5001:5000"
