---
version: "3"
services:
  frontend:
    # build:
    #   context: ./frontend
    #   dockerfile: ./frontend/Dockerfile
    image: frontend:latest
    expose:
      - "3000"
    # {HOST PORT}: {CONTAINER PORT}
    ports:
      - "3000:3000"
    links:
      - backend
    networks:
      - app-test
  backend:
    # context: ./backend
    # dockerfile: ./backend/Dockerfile
    image: backend:latest
    container_name: backend
    expose:
      - "5000"
    networks:
      - app-test
    ports:
      - "5001:5000"

networks:
    app-test:
        driver: bridge
